apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "k8s-chef-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-chef-server.name" . }}
    helm.sh/chart: {{ include "k8s-chef-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-chef-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8s-chef-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.persistence.nfs.enabled }}
          volumeMounts:
          - name: data
            mountPath: /etc/opscode
            subPath: "{{ .Values.persistence.nfs.subPath }}/chef_home_directory"
          - name: data
            mountPath: /var/opt/opscode
            subPath: "{{ .Values.persistence.nfs.subPath }}/your_data_directory"
          - name: data
            mountPath: /var/opt/chef-backup
            subPath: "{{ .Values.persistence.nfs.subPath }}/your_backup_directory"
            {{- if .Values.customSSL }}
          - name: crt
            mountPath: "{{ .Values.customSSL.path }}/crt"
          - name: key
            mountPath: "{{ .Values.customSSL.path }}/key"
            {{- end -}}
        {{- end -}}
        {{- if .Values.persistence.persistentVolume.enabled }}
          volumeMounts:
          - name: chef-home-directory
            mountPath: /etc/opscode
            subPath: "{{ .Values.persistence.nfs.subPath }}/chef_home_directory"
          - name: chef-data-directory
            mountPath: /var/opt/opscode
            subPath: "{{ .Values.persistence.nfs.subPath }}/your_data_directory"
          - name: chef-backup-directory
            mountPath: /var/opt/chef-backup
            subPath: "{{ .Values.persistence.nfs.subPath }}/your_backup_directory"
            {{- if .Values.customSSL }}
          - name: crt
            mountPath: "{{ .Values.customSSL.path }}/crt"
          - name: key
            mountPath: "{{ .Values.customSSL.path }}/key"
            {{- end -}}
        {{- end -}}
        {{- if .Values.persistence.nfs.enabled }}
      volumes:
        - name: data
          nfs:
            path: {{ .Values.persistence.nfs.path }}
            server: {{ .Values.persistence.nfs.server }}
        {{- if .Values.customSSL }}
        - name: crt
          secret:
            secretName: "{{ include "k8s-chef-server.fullname" . }}-crt"
        - name: key
          secret:
            secretName: "{{ include "k8s-chef-server.fullname" . }}-key"
        {{- end }}
        {{- end -}}
        {{- if .Values.persistence.persistentVolume.enabled }}
      volumes:
        - name: chef-home-directory
          persistentVolumeClaim:
            claimName: chef-home-directory
        - name: chef-data-directory
          persistentVolumeClaim:
            claimName: chef-data-directory
        - name: chef-backup-directory
          persistentVolumeClaim:
            claimName: chef-backup-directory
        {{- if .Values.customSSL }}
        - name: crt
          secret:
            secretName: "{{ include "k8s-chef-server.fullname" . }}-crt"
        - name: key
          secret:
            secretName: "{{ include "k8s-chef-server.fullname" . }}-key"
        {{- end }}
        {{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
