{{- if .Values.customSSL.enabled }}
kind: Secret
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "k8s-chef-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: "{{ include "k8s-chef-server.fullname" . }}-key"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  key.key: {{ tpl (.Files.Get "custom-ssl/key.key") . | b64enc | quote }}
{{- end }}
